# SQLite compile definitions on top of libsqlite3-sys's bundled defaults.
[env]
LIBSQLITE3_FLAGS = "-DSQLITE_DQS=0 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS=1 -DSQLITE_ENABLE_MATH_FUNCTIONS=1 -USQLITE_DEFAULT_FOREIGN_KEYS"
