[
  layers: [
    transport: ["VialKeeper.HTTP.*", "VialKeeper.WebUI", "VialKeeper.WebUI.*"],
    application: [
      "VialKeeper.Documents",
      "VialKeeper.Changes",
      "VialKeeper.Query",
      "VialKeeper.Views",
      "VialKeeper.MaterializedViews",
      "VialKeeper.Federation",
      "VialKeeper.Federation.Executor",
      "VialKeeper.Federation.Normalizer",
      "VialKeeper.Federation.BookmarkCodec",
      "VialKeeper.Federation.Ordering",
      "VialKeeper.Federation.SourceCursor",
      "VialKeeper.Federation.SourceDocument",
      "VialKeeper.Federation.SavedQueries",
      "VialKeeper.Replication",
      "VialKeeper.Replication.WireCompression",
      "VialKeeper.Attachments",
      "VialKeeper.Maintenance",
      "VialKeeper.Observability.Dashboard"
    ],
    runtime: [
      "VialKeeper.Runtime.*",
      "VialKeeper.Replication.JobManager",
      "VialKeeper.Query.Subscriptions",
      "VialKeeper.Query.Subscription",
      "VialKeeper.Query.SubscriptionHub",
      "VialKeeper.Query.SubscriptionSupervisor"
    ],
    storage: [
      "VialKeeper.Storage",
      "VialKeeper.Storage.Adapter",
      "VialKeeper.Storage.Results",
      "VialKeeper.Storage.Ports",
      "VialKeeper.Storage.Ports.*",
      "VialKeeper.Storage.BackendContext",
      "VialKeeper.Storage.OpaqueHandle",
      "VialKeeper.Storage.OpaqueHandle.Server",
      "VialKeeper.Storage.PhysicalAllowlist",
      "VialKeeper.Storage.BoundaryGuard",
      "VialKeeper.Storage.Registry",
      "VialKeeper.Storage.Transaction",
      "VialKeeper.Storage.Lifecycle",
      "VialKeeper.Storage.RequestValidation",
      "VialKeeper.Storage.ContextRef",
      "VialKeeper.Storage.Sentinel",
      "VialKeeper.Storage.Sentinel.*",
      "VialKeeper.Storage.Memory",
      "VialKeeper.Storage.Memory.*",
      "VialKeeper.Storage.Services",
      "VialKeeper.Storage.Services.*",
      "VialKeeper.Attachments.FilesystemStore",
      "VialKeeper.Attachments.Compression"
    ],
    sqlite_backend: ["VialKeeper.Storage.SQLite", "VialKeeper.Storage.SQLite.*"],
    core: [
      "VialKeeper.Domain.*",
      "VialKeeper.Revisions.*",
      "VialKeeper.Integrity.*",
      "VialKeeper.JSON.*",
      "VialKeeper.Retention.*",
      "VialKeeper.Commands",
      "VialKeeper.Query.*",
      "VialKeeper.Error",
      "VialKeeper.Headers",
      "VialKeeper.UUID",
      "VialKeeper.DurableFS",
      "VialKeeper.PathSafety",
      "VialKeeper.DatabaseBundle",
      "VialKeeper.Attachments.Manifest",
      "VialKeeper.Attachments.MetadataRequest",
      "VialKeeper.Attachments.Orchestration",
      "VialKeeper.Attachments.Ticket",
      "VialKeeper.Attachments.Store",
      "VialKeeper.Attachments.Representation",
      "VialKeeper.Replication.BlobRepresentationStream",
      "VialKeeper.Replication.ZstdFrame"
    ],
    observability: "VialKeeper.Observability.*"
  ],
  deps: [
    forbidden: [
      {:core, :transport},
      {:core, :runtime},
      {:core, :storage},
      {:core, :sqlite_backend},
      {:storage, :transport},
      {:storage, :sqlite_backend},
      {:runtime, :transport},
      {:runtime, :sqlite_backend},
      {:application, :sqlite_backend},
      {:transport, :sqlite_backend},
      {:observability, :sqlite_backend}
    ]
  ],
  calls: [
    forbidden: [
      {
        [
          "VialKeeper.Runtime.*",
          "VialKeeper.Application",
          "VialKeeper.Diagnostics",
          "VialKeeper.Domain.*",
          "VialKeeper.Query.*",
          "VialKeeper.View.*",
          "VialKeeper.Retention.*",
          "VialKeeper.Federation.*",
          "VialKeeper.Documents",
          "VialKeeper.Changes",
          "VialKeeper.Views",
          "VialKeeper.MaterializedViews",
          "VialKeeper.Replication",
          "VialKeeper.Replication.*",
          "VialKeeper.Attachments",
          "VialKeeper.Commands",
          "VialKeeper.DatabaseBundle",
          "VialKeeper.Storage.Ports",
          "VialKeeper.Storage.Ports.*",
          "VialKeeper.Storage.BackendContext",
          "VialKeeper.Storage.BoundaryGuard",
          "VialKeeper.Storage.Registry",
          "VialKeeper.Storage.Sentinel.*"
        ],
        ["VialKeeper.Storage.SQLite.*", "Exqlite.*", "Exqlite.Sqlite3.*"]
      },
      {
        [
          "VialKeeper.Runtime.*",
          "VialKeeper.Application",
          "VialKeeper.Diagnostics",
          "VialKeeper.Domain.*",
          "VialKeeper.Query.*",
          "VialKeeper.View.*",
          "VialKeeper.Views",
          "VialKeeper.MaterializedViews",
          "VialKeeper.DerivedView.*",
          "VialKeeper.Retention.*",
          "VialKeeper.Federation.*",
          "VialKeeper.Documents",
          "VialKeeper.Changes",
          "VialKeeper.Replication",
          "VialKeeper.Replication.*",
          "VialKeeper.Attachments",
          "VialKeeper.Attachments.*",
          "VialKeeper.Commands",
          "VialKeeper.DatabaseBundle",
          "VialKeeper.Observability.*",
          "VialKeeper.Storage.Adapter",
          "VialKeeper.Storage.Ports",
          "VialKeeper.Storage.Ports.*",
          "VialKeeper.Storage.BackendContext",
          "VialKeeper.Storage.BoundaryGuard",
          "VialKeeper.Storage.PhysicalAllowlist",
          "VialKeeper.Storage.Registry",
          "VialKeeper.Storage.Results",
          "VialKeeper.Storage.Transaction",
          "VialKeeper.HTTP.*",
          "VialKeeper.WebUI",
          "VialKeeper.WebUI.*"
        ],
        [
          "VialKeeper.Storage.OpaqueHandle.unwrap",
          "VialKeeper.Storage.OpaqueHandle.backend_unwrap",
          "VialKeeper.Storage.OpaqueHandle.replace",
          "VialKeeper.Storage.OpaqueHandle.drop",
          "VialKeeper.Storage.OpaqueHandle.Server.unwrap",
          "VialKeeper.Storage.OpaqueHandle.Server.backend_unwrap",
          "VialKeeper.Storage.OpaqueHandle.Server.replace",
          "VialKeeper.Storage.OpaqueHandle.Server.drop"
        ]
      }
    ]
  ]
]
