defmodule ElixirDB.ReleaseSteps do
  @moduledoc """
  Mix release `:steps` hook that patches the generated `bin/elixir_db` launcher
  to add the `token` subcommand (`AUTH-002`).

  The launcher is generated by Mix and dispatches subcommands via a shell
  `case`. This step inserts a `token)` arm (after the `version)` arm) that runs
  `ElixirDB.ReleaseCommands.token/0` through the release's `eval` path, which
  boots a clean VM without starting the application — enough to reach the
  release commands module.
  """

  @launcher_relative "bin/elixir_db"

  @doc false
  @spec patch_launcher(Mix.Release.t()) :: Mix.Release.t()
  def patch_launcher(%Mix.Release{} = release) do
    launcher = Path.join(release.path, @launcher_relative)

    case File.read(launcher) do
      {:ok, contents} ->
        patched = inject_token_commands(contents, token_arm())
        File.write!(launcher, patched)
        File.chmod!(launcher, 0o755)
        release

      {:error, reason} ->
        raise "could not read release launcher #{inspect(launcher)}: #{inspect(reason)}"
    end
  end

  # The shell snippet appended to the launcher's command dispatch, after the
  # `version)` arm. It mirrors the `eval)` arm's boot path so the release
  # command runs on a clean VM without starting the application.
  defp token_arm do
    String.trim_trailing("""
      token)
        export_release_sys_config
        exec "$REL_VSN_DIR/elixir" \\
             --cookie "$RELEASE_COOKIE" \\
             --erl-config "$RELEASE_SYS_CONFIG" \\
             --boot "$REL_VSN_DIR/$RELEASE_BOOT_SCRIPT_CLEAN" \\
             --boot-var RELEASE_LIB "$RELEASE_ROOT/lib" \\
             --vm-args "$RELEASE_VM_ARGS" --eval "ElixirDB.ReleaseCommands.token()" -- "$@"
        ;;
    """)
  end

  defp inject_token_commands(contents, token_arm) do
    anchor =
      String.trim_trailing("""
        version)
          echo "$RELEASE_NAME $RELEASE_VSN"
          ;;
      """)

    if String.contains?(contents, "ElixirDB.ReleaseCommands.token()") do
      # Already patched (e.g., release rebuilt without --overwrite).
      contents
    else
      String.replace(
        contents,
        anchor,
        anchor <> "\n\n" <> token_arm,
        global: false
      )
    end
  end
end
